export default {
    addBoardField : ".vs-c-organization-boards__item--add-new",
    addBoardButton : "[class='vs-c-btn vs-c-btn--primary vs-c-btn--spaced vs-c-btn--spaced-sm vs-c-btn--spaced-no-icon vs-u-text--uppercase']",
    addBoardTitle : "[placeholder='Enter title...']", 
    xButton : ".vs-c-modal__body > .el-button > .el-icon-close",
    nextButton : "[name='next_btn']",
    previousButton : "[name='prev_btn']",
    dropdownFields : "[placeholder='Select']",
    importListsFields : "[class='el-select-dropdown__item vs-c-select-dropdown__item vs-c-new-board-dropdown]",
    scrumBoardButton : "[name='type_scrum']",
    kanbanBoardButton : ".vs-c-radio-check",
    imgBoardField : "[class='vs-c-btn vs-c-btn--rounded-square vs-u-width--full']",
    boardList : ".vs-c-list__btn > :nth-child(3)",
    boardSettingsButton : "[data-cy='board-configuration'] > span > div > .vs-c-site-logo",
    deleteBoardButton : "[class='vs-c-btn vs-c-btn--warning vs-c-btn--spaced']",
    finishButton : "div[class='dialog-footer'] button[name='next_btn']",
    saveButton : "[name='save-btn']",
    cancelButton : "[name='cancel-btn']",
    cancelXButton : ".vs-c-modal__header > .el-button > .el-icon-close",
    importListTypeTitle : "[class='el-form-item__label vs-u-text--uppercase']",
    boardUpdateTitleField : "[data-vv-as='board title']",
    boardTypeButton : ".el-tabs__content .vs-c-settings-section-wrapper:nth-of-type(5) .vs-c-btn--link",
    boardTypeChecbox : "[class='vs-c-task-modal-type-dropdown__icon vs-c-icon--lg']",
    updateBUtton : "[type='submit']",
    addButtonSidebar : "[class='vs-c-list__btn vs-c-list-btn--add-new el-tooltip']",
    addBoardSidebar : "[class='el-tooltip__popper is-light el-tooltip-sidebar']"
}